### ISSUE TITLE
Roll with dice with different themes

### ISSUE THREAD

**Issue by clevett** [3d-dice/FDP#1]
I'm interested in using Dice Parser with Dicebox's themes assigned on roll. Here is my use case:

I want to roll `"2d100kl<50"`. 

I want one set of dice to be pink and the other to be yellow.

```
[
{ sides: 100, qty: 1, theme: "#ff22bb" },
{ sides: 100, qty: 1, theme: "#fff222" },
],
```

How do I set two different colors with FDP ?

**Comment by frankieali** [comment]
So, my best answer for now is:
parse your notation 
```javascript
const notation = parser.parseNotation('2d100kl<50')
```
set up a roll with themes
```javascript
const rolling =  [
{ sides: 100, qty: 1, theme: "#ff22bb" },
{ sides: 100, qty: 1, theme: "#fff222" },
]
```
Roll the dice with themes which will pass the results back to the parser that has stored the notation
```javascript
DiceBox.roll(rolling).then(results => {
    const finalResults = parser.parseFinalResults({ rolls: results });
})
```
You just have to make sure that the dice you're rolling matches the number and type of dice sent to parseNotation
