### ISSUE TITLE
Unexpected Mutations

### ISSUE THREAD

**Issue by clevett** [3d-dice/FDP#3]
When I pass a string rolling one dice type such as '2d6' then the dice parser returns a roll and I am able to pass it to my roll announcement as expected. This is working:

![working](https://i.imgur.com/IhlZ3nY.png)

However if I mix roll types such as '2d6+1d20' then the object returned gets mutated some how. I am trying to make copies of it but so far rolls, dice, and count keys keep coming back undefined.

![not working](https://i.imgur.com/k8RSgiy.png)

These are the functions calling dicebox & parser
```
          const diceRollResult: FDDieResult[] = await dicebox.roll(
            diceBoxNotation
          );

          const parserResult: ParsedResults = DRP.parseFinalResults({
            rolls: { ...diceRollResult },
          });

          const rollAnnoucement = {
            announcementRollInfo: {
              parsedRoll: { ...parserResult },
            },
          };
```

I had a similar problem with Dicebox some how mutating my React state. I had to do a map over the returned results to fix it.

**Comment by frankieali** [comment]
So this looks like it's related to [@3d-dice/dice-roller-parser](https://github.com/3d-dice/dice-roller-parser).  I can see from the pics you posted that the first roll is of `type: die` and the second roll is `type: expressionroll`. These have different outputs. You can probably find more information in the dice-roller-parser readme. My reason for creating the [@3d-dice/FDP](https://github.com/3d-dice/FDP) module was an attempt to normalize the data between different roll types. In particular, there's a `recursiveSearch` method in FDP that I use to dig out rolls data.

**Comment by clevett** [comment]
The outputs being slightly different I can work around. The unexpected mutations is an issue. I should be able to make a copy of the result from the parser and it should remain the same as when I copied it.

Do you know what is changing it ? I tried doing both shallow and deep copies as well as object.freeze but every time the dice key was change to undefined.

**Comment by frankieali** [comment]
So there's only two things I can think of at the moment.
1. You need to make sure you feed the notation into the parser before parsing the final results: `DRP.parseNotation('2d6+1d20')`. The parsed notation is saved to the DRP class and will set the expectations for the `.parseFinalResults`
2. parseFinalResults expects an array of roll objects
```
          const parserResult: ParsedResults = DRP.parseFinalResults([{
            rolls: { ...diceRollResult },
          }]);
```
I hope that helps.

**Comment by clevett** [comment]
Thanks! I managed to fix it. It may have been more on mine end than the roller. *blush*
