### ISSUE TITLE
1d3+1d4 throws error

### ISSUE THREAD

**Issue by clevett** [3d-dice/FDP#6]
parseNotation will make a roll object out of a 1d3 but this can't be rolled by Dicebox and it will cause an error. FDP probably needs to check to ensure sides is equal to a typically die and only pass that to Dicebox.

**Comment by frankieali** [comment]
This has been on my todo list for a while. Supporting all non-standard rolls. It's on my list right under rolling just the single percentile die as 'd%'

**Comment by frankieali** [comment]
Also, I have yet to incorporate any real input validations or error handling. That's on my list too.
